### ISSUE TITLE
Can this support colored nonogram puzzle?

### ISSUE THREAD

**Issue by oovm** [ricoriedel/nonogram-rs#1]
This project is really cool, I would like to know if color puzzles are supported.

In a colored puzzle, the same numbers can be adjacent to each other, just in different colors.

**Comment by ricoriedel** [comment]
Sorry for responding so late.
Currently colored puzzles are not supported. However, I think it should be possible to implement. I will definitely look into it as soon as possible.
I will update this issue once I have more to share.

**Comment by ricoriedel** [comment]
The logic of the algorithm would only require minor changes.
But because I never intended to introduce this feature, I would have to restructure almost everything.
It would be easier to rewrite the code from scratch.

For now, this feature will no be introduced.
I'm determined to support it with a 2.0 release, but this will take time.

Please close this issue, if this answers your question.

**Comment by ricoriedel** [comment]
In case you still bother, I have released a new version with support for colored nonograms!

**Comment by oovm** [comment]
Great, I'll see if it fits my needs
